// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Migrationen (prisma migrate deploy) brauchen eine DIREKTE (ungepoolte)
    // Verbindung – über einen Pooler (PgBouncer) können sie fehlschlagen. Vercel/
    // Neon stellen dafür DATABASE_URL_UNPOOLED bzw. POSTGRES_URL_NON_POOLING bereit.
    // Zur Laufzeit nutzt die App weiterhin DATABASE_URL (siehe src/lib/prisma.ts).
    url:
      process.env["DATABASE_URL_UNPOOLED"] ||
      process.env["POSTGRES_URL_NON_POOLING"] ||
      process.env["DATABASE_URL"],
  },
});
